application: helloworld
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /insert
  script: insert.php

- url: /lookup
  script: lookup.php

- url: /searchIndex.html
  script: searchIndex.html

- url: /registerIndex.html
  script: registerIndex.html

- url: /aboutUs.html
  script: aboutUs.html

- url: /.*
  script: home.html




